version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: eventstore
    ports:
      - "5432:5432"
    networks:
      - eventstore_network

networks:
  eventstore_network:
    driver: bridge
